"""Generate a bookmarkable HTML page from aggregated events.

Matches the BD Resource Library aesthetic: dark theme, DM Serif Display + DM Sans,
events grouped by month, region badges per source.
"""
from datetime import datetime, timezone
from typing import List
import html

from scrapers.base import Event


REGION_COLORS = {
    "NorCal": "#0a66c2",   # blue
    "SoCal":  "#ec4899",   # pink
    "Both":   "#10b981",   # green
}

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>BD Events — Bay Area &amp; San Diego</title>
<link rel="alternate" type="text/calendar" title="Subscribe (iCal)" href="events.ics">
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=DM+Sans:wght@400;500;600;700&display=swap');
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: 'DM Sans', sans-serif; background: #0f1419; color: #e7e9ea; line-height: 1.6; }}
.container {{ max-width: 980px; margin: 0 auto; padding: 48px 24px 80px; }}

.hero {{ border-bottom: 1px solid #2f3336; padding-bottom: 32px; margin-bottom: 40px; }}
.badge {{ display: inline-block; font-size: 11px; font-weight: 700; letter-spacing: 2px;
  text-transform: uppercase; color: #f59e0b; border: 1px solid #f59e0b33; padding: 4px 12px;
  border-radius: 20px; margin-bottom: 16px; }}
h1 {{ font-family: 'DM Serif Display', serif; font-size: 42px; color: #fff; line-height: 1.15; margin-bottom: 8px; }}
.subtitle {{ color: #71767b; font-size: 15px; margin-bottom: 24px; }}

.meta-bar {{ display: flex; flex-wrap: wrap; gap: 12px; align-items: center; margin-top: 16px; }}
.subscribe {{ display: inline-flex; align-items: center; gap: 8px; background: #0a66c2;
  color: white; padding: 10px 18px; border-radius: 10px; text-decoration: none;
  font-weight: 600; font-size: 14px; transition: background 0.15s; }}
.subscribe:hover {{ background: #0958a8; }}
.stat-pill {{ background: #16181c; border: 1px solid #2f3336; border-radius: 20px;
  padding: 6px 14px; font-size: 13px; color: #cfd4d8; }}
.stat-pill strong {{ color: #fff; }}

.month-section {{ margin-bottom: 48px; }}
.month-header {{ font-family: 'DM Serif Display', serif; font-size: 26px; color: #fff;
  margin-bottom: 16px; padding-left: 14px; border-left: 3px solid #f59e0b; }}

.event {{ background: #16181c; border: 1px solid #2f3336; border-radius: 12px;
  padding: 18px 22px; margin-bottom: 10px; display: grid;
  grid-template-columns: 80px 1fr; gap: 18px; align-items: start;
  transition: border-color 0.15s; }}
.event:hover {{ border-color: #4b5563; }}
.event-date {{ text-align: center; padding-top: 4px; }}
.event-date .day {{ font-family: 'DM Serif Display', serif; font-size: 32px;
  color: #f59e0b; line-height: 1; }}
.event-date .dow {{ font-size: 11px; color: #71767b; text-transform: uppercase;
  letter-spacing: 1.5px; margin-top: 4px; font-weight: 600; }}

.event-body a.event-title {{ color: #fff; font-size: 16px; font-weight: 600;
  text-decoration: none; line-height: 1.35; display: block; margin-bottom: 6px; }}
.event-body a.event-title:hover {{ color: #f59e0b; }}
.event-meta {{ display: flex; flex-wrap: wrap; gap: 10px; margin-top: 8px;
  font-size: 12px; color: #71767b; align-items: center; }}
.source-tag {{ font-weight: 600; font-size: 11px; padding: 3px 10px; border-radius: 12px;
  letter-spacing: 0.4px; }}
.location {{ color: #a0a4a8; }}
.time-badge {{ color: #cfd4d8; font-weight: 500; }}

.empty {{ text-align: center; padding: 60px 20px; color: #71767b; background: #16181c;
  border: 1px dashed #2f3336; border-radius: 12px; }}

footer {{ margin-top: 64px; padding-top: 24px; border-top: 1px solid #2f3336;
  color: #71767b; font-size: 12px; line-height: 1.7; }}
footer a {{ color: #cfd4d8; }}

@media (max-width: 600px) {{
  h1 {{ font-size: 32px; }}
  .event {{ grid-template-columns: 60px 1fr; gap: 12px; padding: 14px 16px; }}
  .event-date .day {{ font-size: 26px; }}
}}
</style>
</head>
<body>
<div class="container">
  <div class="hero">
    <div class="badge">BD RESOURCE LIBRARY — 12</div>
    <h1>BD Events</h1>
    <p class="subtitle">Aggregated AEC industry events — Bay Area &amp; San Diego. Updated automatically.</p>
    <div class="meta-bar">
      <a class="subscribe" href="events.ics" download>📅 Subscribe in Outlook (.ics)</a>
      <span class="stat-pill"><strong>{event_count}</strong> upcoming events</span>
      <span class="stat-pill"><strong>{source_count}</strong> sources</span>
      <span class="stat-pill">Updated {updated_at}</span>
    </div>
  </div>

  {body}

  <footer>
    Generated by the BD Events Aggregator. The .ics feed at
    <a href="events.ics">events.ics</a> can be subscribed in Outlook, Apple Calendar, or
    Google Calendar — events update automatically every few hours.<br>
    Sources tracked: {sources_list}
  </footer>
</div>
</body>
</html>
"""

EMPTY_BODY = '<div class="empty">No upcoming events found. The aggregator may be having trouble — check back tomorrow.</div>'


def write_html(events: List[Event], path: str) -> None:
    sources_seen = sorted({e.source for e in events})

    if not events:
        body = EMPTY_BODY
    else:
        body = _render_grouped(events)

    page = PAGE.format(
        event_count=len(events),
        source_count=len(sources_seen),
        updated_at=datetime.now(timezone.utc).strftime("%b %d, %Y at %H:%M UTC"),
        body=body,
        sources_list=", ".join(html.escape(s) for s in sources_seen),
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(page)
    print(f"  Wrote HTML page to {path}")


def _render_grouped(events: List[Event]) -> str:
    """Group events by year-month and render each group as a section."""
    sections = []
    current_key = None
    current_buf = []

    def flush():
        if current_key and current_buf:
            heading = current_key  # already 'May 2026'
            sections.append(
                f'<div class="month-section">'
                f'<h2 class="month-header">{html.escape(heading)}</h2>'
                + "\n".join(current_buf)
                + "</div>"
            )

    for ev in events:
        key = ev.start.strftime("%B %Y")
        if key != current_key:
            flush()
            current_key = key
            current_buf = []
        current_buf.append(_render_event(ev))
    flush()
    return "\n".join(sections)


def _render_event(ev: Event) -> str:
    day = ev.start.strftime("%-d") if hasattr(ev.start, "strftime") else str(ev.start.day)
    dow = ev.start.strftime("%a")
    region_color = REGION_COLORS.get(ev.source_region, "#6b7280")

    time_part = ""
    # Only show time if it's not midnight UTC (which we use as date-only fallback)
    if ev.start.hour != 0 or ev.start.minute != 0:
        local_time = ev.start.strftime("%-I:%M %p")
        time_part = f'<span class="time-badge">🕐 {local_time}</span>'

    location_part = ""
    if ev.location:
        loc_short = html.escape(ev.location[:80])
        location_part = f'<span class="location">📍 {loc_short}</span>'

    title_html = html.escape(ev.title)
    url = html.escape(ev.url or "#")

    return f'''<div class="event">
  <div class="event-date">
    <div class="day">{day}</div>
    <div class="dow">{dow}</div>
  </div>
  <div class="event-body">
    <a class="event-title" href="{url}" target="_blank" rel="noopener">{title_html}</a>
    <div class="event-meta">
      <span class="source-tag" style="background: {region_color}22; color: {region_color};">{html.escape(ev.source)}</span>
      {time_part}
      {location_part}
    </div>
  </div>
</div>'''
